abstract class AppStates {}
class InitialState extends AppStates{}
class GetIndexItemBottomNavigationBar extends AppStates{}
class ChangeBottomSheetIsOpenState extends AppStates{}
class CreateDatabaseState extends AppStates{}
class InsertToDatabaseState extends AppStates{}
class UpdateFromDatabaseState extends AppStates{}
class GetDataFromDatabaseState extends AppStates{}
class DeleteDataFromDatabaseState extends AppStates{}
